### ISSUE TITLE
Add automated documentation generation

### ISSUE THREAD

**Issue by thibaudcolas** [thibaudcolas/draftjs-filters#19]
At the moment, the project's documentation is limited to what is in the README, and a short note about filtering limitation in `docs/`. It would be nice if there was more complete documentation generated automatically: a full API reference, with links back to the source code, based on the Flow types (or JSDoc).

Ideally this would be generating Markdown so it can be versioned with the code in Git/GitHub.

Tools to consider & useful info:

- https://github.com/documentationjs/documentation
- https://github.com/esdoc/esdoc
- https://survivejs.com/maintenance/documentation/readme/
- https://survivejs.com/maintenance/documentation/api/

**Comment by rjseymour66** [comment]
Hi,
I am a professional technical writer and am eager to contribute to my first Github project.

I keep seeing JSDoc being discussed for similar projects, so I think that sounds as good as any solution.  Would you like me to help?

- Ryan

**Comment by thibaudcolas** [comment]
Hey @rjseymour66, thank you for offering your help! Someone else has already had a shot at this (#26), so I think I'll go with their implementation.

Generally JSDoc would be a very good fit for such use case, but here the project already has annotations with [Flow](https://flow.org/) so it would be even better if the documentation generator used these.

**Comment by thibaudcolas** [comment]
:tada: This issue is fixed in v2.2.1, available on npm: [draftjs-filters@2.2.1](https://www.npmjs.com/package/draftjs-filters).

<p align="right">
Generated by :package::rocket: <a href="https://github.com/semantic-release/semantic-release">semantic-release</a>
</p>
