### ISSUE TITLE
Add an HTML test page to the demo site with test content for the filters

### ISSUE THREAD

**Issue by thibaudcolas** [thibaudcolas/draftjs-filters#20]
The filters sometimes encounter quite intricate HTML. It would be great if we had a page with test content, so we can copy-paste it while manually testing the filters. Something that contains sample rich text as HTML, as well as a large range of HTML tags to see what happens.

I barely started at #16 but there is much more to be done.

**Comment by hiteshpr** [comment]
Hi, can I work on this issue?

**Comment by thibaudcolas** [comment]
Hey @hiteshpr, sure! You can start from the commit in #16 (feel free to make a separate PR), which creates the page and adds links to it but doesn't contain any test content.

For test content, I'm not entirely sure just yet what would be the most interesting. I guess "every possible HTML tag" might be interesting (like the existing [test documents](https://github.com/thibaudcolas/draftjs-filters#external-sources) that have a sample of every possible rich text format). But anything is better than nothing, so the page will be useful even with just a handful of formats (heading levels, lists, etc)
