### ISSUE TITLE
Add new sideEffects flag for Webpack 4

### ISSUE THREAD

**Issue by thibaudcolas** [thibaudcolas/draftjs-filters#24]
Webpack 4 comes with a new [`sideEffects`](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free) flag for package authors to add in their package.json. This makes it possible for Webpack to do further optimisations in its compilation.

I think the filters are free of side effects by Webpack's definition, so they should have the flag set to `false`. It would be nice to confirm this with some kind of test (or a third-party tool that does the check?), and to know how much of a performance benefit it is for this package.

- [ ] Add new `"sideEffects": false,` flag in package.json
- [ ] Write a test, or integrate a tool, that checks for this
- [ ] Assess performance benefit of using the new flag

**Comment by JipSterk** [comment]
@thibaudcolas i would like to work on this but i dont really know how i would write a test for this.

**Comment by thibaudcolas** [comment]
@JipSterk I think we can go without tests (see my comment in #25) – all the projects I checked out have just added the flag without blinking:

- https://github.com/marionettejs/backbone.marionette/pull/3577
- https://github.com/ReactTraining/history/pull/597
- https://github.com/kensho-technologies/orama/pull/34

I think the best way to properly test this would be to have a linting rule (ESLint or Flowlint) for it, but that's a lot of work.

**Comment by thibaudcolas** [comment]
Fixed in #25.
