### ISSUE TITLE
BUG: Pasting subscript and superscript from Word removes the formatting, even when they are enabled

### ISSUE THREAD

**Issue by coredumperror** [thibaudcolas/draftjs-filters#33]
I posted a detailed bug report for this over at springload/draftail/issues/200, but then realized that it might actually be a bug in this project. I really hope _someone_ can help me, because I'm completely stumped. >_<

**Comment by thibaudcolas** [comment]
See https://github.com/springload/draftail/issues/200 – this isn’t an issue with draftjs-filters (it only does filtering of content already converted from rich text by Draft.js, not of rich text / HTML soup directly), so I’ll keep track of a potential fix on the Draftail issue.
